[package]
name = "header-parsing"
version = "0.0.0"
description = "Parsing utilities for http headers"
publish = false

license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
http.workspace = true
